
const chatDetails = [
  {
    "id": 1,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Hello world!",
    "messageNo": 1,
  },
  {
    "id": 2,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Nam porttitor nibh at nisl bibendum egestas.",
    "messageNo": 3,
  },
  {
    "id": 3,
    "isMe": true,
    "profile": "",
    "message": "Nunc tristique turpis et lacus pellentesque auctor.",
    "messageNo": 1,
  },
  {
    "id": 4,
    "isMe": true,
    "profile": "",
    "message": "Fine.",
    "messageNo": 2,
  },
  {
    "id": 5,
    "isMe": true,
    "profile": "",
    "message": "Maecenas consequat sem ut augue ultricies, a lacinia diam sodales.",
    "messageNo": 3,
  },
  {
    "id": 6,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Fusce et nunc facilisis tortor tristique sodales id quis quam.",
    "messageNo": 0,
  },
  {
    "id": 6,
    "isMe": true,
    "profile": "",
    "message": "Vestibulum porttitor orci vitae dolor lacinia, sit amet tempor turpis placerat.",
    "messageNo": 1,
  },
  {
    "id": 6,
    "isMe": true,
    "profile": "",
    "message": "Proin rhoncus ex nec molestie porta.",
    "messageNo": 3,
  },
  {
    "id": 7,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Nulla non tortor sed odio porta facilisis.",
    "messageNo": 1,
  },
  {
    "id": 8,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Sed rhoncus justo quis dui pretium molestie.",
    "messageNo": 3,
  },
  {
    "id": 9,
    "isMe": true,
    "profile": "",
    "message": "Integer maximus elit at rutrum aliquam.",
    "messageNo": 1,
  },
  {
    "id": 10,
    "isMe": true,
    "profile": "",
    "message": "Aliquam accumsan elit id pellentesque placerat.",
    "messageNo": 3,
  },
  {
    "id": 11,
    "isMe": false,
    "profile": "https://i.pinimg.com/originals/cd/63/95/cd63958613ce86afc242b1bcc5812bba.jpg",
    "message": "Ut placerat quam congue feugiat rhoncus.",
    "messageNo": 0,
  },
  {
    "id": 12,
    "isMe": true,
    "profile": "",
    "message": "Vestibulum sollicitudin neque sed erat consequat imperdiet.",
    "messageNo": 0,
  },
];